### ISSUE TITLE
Orb of Wonder

### ISSUE THREAD

**Issue by Kircough** [keyteki/keyteki#2497]
![image](https://user-images.githubusercontent.com/82804147/115205025-0a948480-a0f1-11eb-9dcf-ef1fdc3ca39e.png)

Orb of Wonder appears to be in house Brobnar and can't be played. Deck is Lt. “Butterfly” Mitchen.

**Comment by SteVader** [comment]
This has been fixed in #2473 - please see the note from @romanogit here though https://github.com/keyteki/keyteki/issues/2443#issuecomment-821844883

It might be the case that you'll need to delete and re-import the deck.

**Comment by romanogit** [comment]
It seems that it it still not working properly live. I will double check.

**Comment by romanogit** [comment]
Confirmed now lobby is working. You need to delete and import your deck again.
