### ISSUE TITLE
Smite Not Removing Stun Token

### ISSUE THREAD

**Issue by Jarimy123** [keyteki/keyteki#276]
When playing Smite on a creature with a Stun Token it just exhausts the creature, it doesn't remove the Stun token.

**Comment by 4ugeistr** [comment]
Similair issue with [Grey Rider].
It doesn't remove the stun and doesn't exhaust.
"Ready and fight" "Ready and use" abilities should automatically exhaust and remove stun.
![image](https://user-images.githubusercontent.com/23107141/62505387-249b1000-b805-11e9-8718-cc18786d8d61.png)

**Comment by romanogit** [comment]
@Jarimy123 , are you sure the card is `Smite`?

https://keyforge-compendium.com/sets/2-aoa/cards/224-smite

Card says:

> Card Text Play: Ready and fight with a friendly creature. Deal 2D to the attacked creature’s neighbors.

![image](https://user-images.githubusercontent.com/2104075/62534000-61bfcc00-b81e-11e9-9fc7-8608884aff30.png)

**Comment by romanogit** [comment]
@Jarimy123 : I understand what you mean now, I did not read "Ready and fight". I will try to reproduce this one.

**Comment by romanogit** [comment]
I was able to recreate:

![image](https://user-images.githubusercontent.com/2104075/62621957-8cc81f80-b8f3-11e9-852e-520ff22ba2fd.png)

It exhausted Groke, but did not remove the Stun:

![image](https://user-images.githubusercontent.com/2104075/62621997-a5d0d080-b8f3-11e9-9cfb-fdbc05d83ec9.png)

**Comment by romanogit** [comment]
Fixed and created PR

**Comment by romanogit** [comment]
Deployed. Can you close @cryogen .?

**Comment by Jarimy123** [comment]
It's not fixed.  Seems worse now.  I just had a stunned Helper Bot, used Smite, and it destroyed him.  
![SMITE](https://user-images.githubusercontent.com/46849213/63296211-9ad75200-c29c-11e9-9c8f-b36c50908023.jpg)

**Comment by romanogit** [comment]
I added an extra assertion to the test case and it continues to pass. Maybe something different now.

**Comment by Jarimy123** [comment]
I have a deck that used Smite out of house a lot to unstun - I will continue trying it and will screen shot instances it destroys the creature and post them here if it continues to happe.
